[package]
name = "testing_hstring_bindings"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hstring = {git = "https://github.com/largenumberhere/hstring.git", version = "0.0.6" }
